### ISSUE TITLE
Compile error : unexpected close delimiter: `]`

### ISSUE THREAD

**Issue by aurabindo** [jamesmunns/nrf52dk-sys#10]
I am getting the following error on compiling:

```
   Compiling nrf52dk-sys v0.2.0 (file:///home/aj/learning/embedded/rust/nrf52/nrf52dk-sys)
error: unexpected close delimiter: `]`
     --> /home/aj/learning/embedded/rust/nrf52/nrf52dk-sys/target/thumbv7em-none-eabihf/debug/build/nrf52dk-sys-72d3b0d776d9ac48/out/bindings.rs:10119:32
      |
10119 | #[derive(Copy, Clone)]; 4usize ] , _bindgen_union_align : u32 , }#[test]
      |                                ^

error: Could not compile `nrf52dk-sys`.
```

In addition to that I have quite a lot of warnings which I suppressed with corresponding `-Wno-...`

**Comment by anxiousmodernman** [comment]
Union types in bindgen have had their generated representation change a few times. We've sort of been chasing after bindgen versions. @aurabindo can you try compiling with this PR? https://github.com/jamesmunns/nrf52dk-sys/pull/9

**Comment by aurabindo** [comment]
I'm getting an error related to incremental compilation. I did run `unset CARGO_INCREMENTAL`

```
   Compiling nrf52dk-sys v0.2.0 (file:///home/aj/learning/embedded/rust/nrf52/nrf52dk-sys)
error: can't perform LTO when compiling incrementally

error: Could not compile `nrf52dk-sys`.

To learn more, run the command again with --verbose.
```

Any suggestions on how fix it ?

**Comment by anxiousmodernman** [comment]
@aurabindo You might need to explicitly set 0? Try `CARGO_INCREMENTAL=0`. For example,

```
$ CARGO_INCREMENTAL=0 xargo build --example blinky
```

**Comment by aurabindo** [comment]
@anxiousmodernman  It builds for me, thank you.
