### ISSUE TITLE
Port this to the fresh embedded ecosystem 

### ISSUE THREAD

**Issue by eupn** [jamesmunns/nrf52dk-sys#15]
Can you guys please port this awesome project to the recent programmer's model that doesn't require unstable features (like `asm` or `lang-items`)? I want to start a project with this crate, since I need BLE and this seems to be an only option, but it also seems kind of outdated (especially considering rapid change rate in embedded rust area).

**Comment by zackangelo** [comment]
I'm in the same boat. I'm naively wondering if it's possible to just use the SDK bindings for interacting with the BLE SoftDevice and use the rust-embedded stuff for everything else.

**Comment by eupn** [comment]
@zackangelo I think yes, but one should keep in mind that some of the hardware resources are used by SoftDevice and, thus, should be consumed in a way that doesn't allow interacting with those resources from Rust code. 

For example, this function consumes RTC0 which is used by SoftDevice, so one is no longer able to use this RTC0 peripheral from safe Rust code:

```rust
fn init_softdevice(_rtc0: RTC0) {
}
```

Linker file is also should take into account parts of FLASH and SRAM that are consumed by SoftDevice and shouldn't allocate those areas for Rust code.
