### ISSUE TITLE
docs: rustup component add rust-src

### ISSUE THREAD

**Issue by anxiousmodernman** [jamesmunns/nrf52dk-sys#3]
Is there an error in the docs?
![rustup](https://user-images.githubusercontent.com/396004/27161333-aea277d2-5148-11e7-89c2-451f38d198cb.png)

Here: https://github.com/jamesmunns/nrf52dk-sys/blob/master/SETUP.md#6-install-rust-core-source

Should this just be `rustup component add rust-src`?

**Comment by anxiousmodernman** [comment]
Going through this for the DC meetup; (got my firmware compiling with the rest of the docs, btw)

**Comment by jamesmunns** [comment]
Yup, that's a copy paste error. I'll fix that in a bit. Thanks!
